name: Test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache node_modules, .next/cache, .npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .next/cache
            .npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: yarn install

      - name: build
        run: yarn build
